#!/bin/bash
# scripts/parity-analysis/main.sh
# Main orchestrator for production vs staging parity analysis and automated remediation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

# Configuration
CONFIG_FILE="$SCRIPT_DIR/../../config/parity-analysis.yaml"
REPORT_DIR="$SCRIPT_DIR/../../reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="$REPORT_DIR/parity-analysis-$TIMESTAMP.md"

# Remediation scripts
REMEDIATION_DIR="$SCRIPT_DIR/../remediation"

main() {
    log_critical "🚀 STARTING COMPREHENSIVE PARITY ANALYSIS"

    # Setup
    setup_environment

    # Execute analysis tiers
    run_tier1_analysis
    run_tier2_analysis

    # Generate final report
    generate_final_report

    # Auto-remediation if enabled
    if [[ "${AUTO_REMEDIATE:-false}" == "true" ]]; then
        run_auto_remediation
    fi

    # Display results
    display_results

    log_critical "✅ PARITY ANALYSIS COMPLETE"
}

setup_environment() {
    log_info "Setting up analysis environment..."

    # Validate tools
    validate_tools

    # Create report directory
    mkdir -p "$REPORT_DIR"

    # Initialize report
    cat > "$REPORT_FILE" <<EOF
# VendFinder Production vs Staging Parity Analysis
**Generated:** $(date)
**Analyst:** Automated Parity Analysis System
**Scope:** Complete infrastructure, services, and workflow comparison

---

EOF

    log_info "✅ Environment setup complete"
}

run_tier1_analysis() {
    log_critical "🏗️  TIER 1: INFRASTRUCTURE PARITY ANALYSIS"

    if [[ -x "$SCRIPT_DIR/tier1-infrastructure.sh" ]]; then
        log_info "Running Tier 1 infrastructure analysis..."
        "$SCRIPT_DIR/tier1-infrastructure.sh" "$REPORT_FILE"
        log_info "✅ Tier 1 analysis complete"
    else
        log_error "❌ Tier 1 analysis script not found or not executable"
        add_discrepancy "$REPORT_FILE" "CRITICAL" "Missing Analysis Component" \
            "Tier 1 infrastructure analysis script is missing" \
            "Restore tier1-infrastructure.sh script"
    fi
}

run_tier2_analysis() {
    log_critical "🔧 TIER 2: SERVICE HEALTH & API PARITY ANALYSIS"

    if [[ -x "$SCRIPT_DIR/tier2-services.sh" ]]; then
        log_info "Running Tier 2 service health analysis..."
        "$SCRIPT_DIR/tier2-services.sh" "$REPORT_FILE"
        log_info "✅ Tier 2 analysis complete"
    else
        log_error "❌ Tier 2 analysis script not found or not executable"
        add_discrepancy "$REPORT_FILE" "CRITICAL" "Missing Analysis Component" \
            "Tier 2 service health analysis script is missing" \
            "Restore tier2-services.sh script"
    fi
}

generate_final_report() {
    log_info "📊 Generating final analysis report..."

    # Add summary section
    cat >> "$REPORT_FILE" <<EOF

## Executive Summary

$(date) - Parity analysis completed across all tiers.

### Critical Issues Found
EOF

    # Count issues by priority
    local critical_count high_count medium_count low_count
    critical_count=$(grep -c "CRITICAL:" "$REPORT_FILE" 2>/dev/null | head -1 || echo "0")
    high_count=$(grep -c "HIGH:" "$REPORT_FILE" 2>/dev/null | head -1 || echo "0")
    medium_count=$(grep -c "MEDIUM:" "$REPORT_FILE" 2>/dev/null | head -1 || echo "0")
    low_count=$(grep -c "LOW:" "$REPORT_FILE" 2>/dev/null | head -1 || echo "0")

    cat >> "$REPORT_FILE" <<EOF
- **CRITICAL**: $critical_count issues requiring immediate attention
- **HIGH**: $high_count issues requiring prompt resolution
- **MEDIUM**: $medium_count issues for planned resolution
- **LOW**: $low_count minor issues and improvements

### Next Steps
EOF

    # Add remediation recommendations
    if [[ "$critical_count" -gt 0 ]]; then
        cat >> "$REPORT_FILE" <<EOF
1. **Immediate Action Required**: Run emergency remediation for $critical_count critical issues
   \`\`\`bash
   $REMEDIATION_DIR/emergency-fix-critical-gaps.sh
   \`\`\`
EOF
    fi

    if [[ "$high_count" -gt 0 ]]; then
        cat >> "$REPORT_FILE" <<EOF
2. **High Priority**: Address $high_count high-priority issues within 24 hours
   \`\`\`bash
   $REMEDIATION_DIR/auto-fix-critical-gaps.sh
   \`\`\`
EOF
    fi

    cat >> "$REPORT_FILE" <<EOF

### Report Location
**Full Report**: \`$REPORT_FILE\`

---
*Generated by VendFinder Automated Parity Analysis System*
EOF

    log_info "✅ Final report generated: $REPORT_FILE"
}

run_auto_remediation() {
    log_critical "🤖 AUTO-REMEDIATION ENABLED - FIXING CRITICAL ISSUES"

    local critical_count
    critical_count=$(grep -c "🚨 CRITICAL:" "$REPORT_FILE" || echo "0")

    if [[ "$critical_count" -gt 0 ]]; then
        log_warn "Found $critical_count critical issues - running emergency remediation"

        if [[ -x "$REMEDIATION_DIR/emergency-fix-critical-gaps.sh" ]]; then
            log_info "Executing emergency remediation..."
            "$REMEDIATION_DIR/emergency-fix-critical-gaps.sh" || log_error "Emergency remediation failed"
        else
            log_error "Emergency remediation script not found"
        fi
    else
        log_info "No critical issues found - skipping emergency remediation"
    fi

    # Run standard auto-fixes for high priority issues
    local high_count
    high_count=$(grep -c "⚠️ HIGH:" "$REPORT_FILE" || echo "0")

    if [[ "$high_count" -gt 0 ]] && [[ -x "$REMEDIATION_DIR/auto-fix-critical-gaps.sh" ]]; then
        log_info "Running automated fixes for $high_count high-priority issues..."
        "$REMEDIATION_DIR/auto-fix-critical-gaps.sh" || log_error "Auto-fix remediation failed"
    fi

    log_info "✅ Auto-remediation complete"
}

display_results() {
    log_critical "📋 ANALYSIS RESULTS SUMMARY"

    # Display issue counts
    local critical_count high_count medium_count low_count total_count
    critical_count=$(grep -c "CRITICAL:" "$REPORT_FILE" 2>/dev/null | head -1 | tr -d '\n' || echo "0")
    high_count=$(grep -c "HIGH:" "$REPORT_FILE" 2>/dev/null | head -1 | tr -d '\n' || echo "0")
    medium_count=$(grep -c "MEDIUM:" "$REPORT_FILE" 2>/dev/null | head -1 | tr -d '\n' || echo "0")
    low_count=$(grep -c "LOW:" "$REPORT_FILE" 2>/dev/null | head -1 | tr -d '\n' || echo "0")
    total_count=$(( ${critical_count:-0} + ${high_count:-0} + ${medium_count:-0} + ${low_count:-0} ))

    log_info "Issues Found:"
    log_info "  🚨 CRITICAL: $critical_count"
    log_info "  ⚠️ HIGH:     $high_count"
    log_info "  🔍 MEDIUM:   $medium_count"
    log_info "  💡 LOW:      $low_count"
    log_info "  📊 TOTAL:    $total_count"

    # Display next steps
    if [[ "$total_count" -eq 0 ]]; then
        log_critical "🎉 NO ISSUES FOUND - ENVIRONMENTS IN PERFECT PARITY!"
    elif [[ "$critical_count" -eq 0 ]] && [[ "$high_count" -eq 0 ]]; then
        log_info "✅ No critical or high-priority issues - system is stable"
    else
        log_warn "⚠️  Action required - review report for remediation steps"
    fi

    log_info "📄 Full report available at: $REPORT_FILE"
}

# Parse command line arguments
AUTO_REMEDIATE=false
VERBOSE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --auto-remediate)
            AUTO_REMEDIATE=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

show_usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Main orchestrator for VendFinder parity analysis system.

OPTIONS:
    --auto-remediate    Enable automatic remediation of critical issues
    --verbose          Enable verbose logging
    --help             Show this help message

EXAMPLES:
    $0                              # Run analysis only
    $0 --auto-remediate            # Run analysis and fix critical issues
    $0 --auto-remediate --verbose  # Run with auto-fix and detailed logging

ENVIRONMENT VARIABLES:
    AUTO_REMEDIATE=true    # Enable auto-remediation
    VERBOSE=true           # Enable verbose logging

EOF
}

# Run main function if script executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi