apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: vendfinder
  labels:
    app: api-gateway
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: vendfinder-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - prod-app
      containers:
        - name: api-gateway
          image: registry.digitalocean.com/vendfinder-registry/api-gateway:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: vendfinder
  labels:
    app: api-gateway
    environment: production
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
