apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: vendfinder
  labels:
    app: elasticsearch
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - prod-heavy
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1000m"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: vendfinder
  labels:
    app: elasticsearch
    environment: production
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
