apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: vendfinder
  labels:
    app: prometheus
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - prod-data
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1000m"
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: vendfinder
  labels:
    app: prometheus
    environment: production
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
