apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-data
  namespace: vendfinder
  labels:
    app: chat-db
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-data
  namespace: vendfinder
  labels:
    app: order-db
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-data
  namespace: vendfinder
  labels:
    app: product-db
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vendor-db-data
  namespace: vendfinder
  labels:
    app: vendor-db
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-db-data
  namespace: vendfinder
  labels:
    app: analytics-db
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
