apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: vendfinder-staging
  labels:
    app: api-gateway
    environment: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: api-staging.vendfinder.com
    http:
      paths:
      - backend:
          service:
            name: api-gateway
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api-staging.vendfinder.com
    secretName: api-staging-vendfinder-tls