apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-data
  namespace: vendfinder-staging
  labels:
    app: chat-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-data
  namespace: vendfinder-staging
  labels:
    app: order-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-data
  namespace: vendfinder-staging
  labels:
    app: product-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vendor-db-data
  namespace: vendfinder-staging
  labels:
    app: vendor-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-db-data
  namespace: vendfinder-staging
  labels:
    app: review-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-data
  namespace: vendfinder-staging
  labels:
    app: user-db
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
