#!/bin/bash

echo "🎯 VendFinder Conventional Commit Examples:"
echo ""
echo "✅ Good examples:"
echo "  feat(auth): add OAuth2 login integration"
echo "  fix(cart): resolve checkout payment processing error"
echo "  docs(api): update authentication endpoint documentation"
echo "  style(ui): improve button hover animations"
echo "  refactor(utils): extract common validation functions"
echo "  perf(search): optimize product query performance"
echo "  test(auth): add unit tests for login service"
echo "  build(docker): update Node.js version to 18.19"
echo "  ci(github): add automated deployment workflow"
echo "  chore(deps): update dependencies to latest versions"
echo ""
echo "❌ Bad examples:"
echo "  Fix bug (missing type)"
echo "  feat: Add new feature. (ends with period)"
echo "  FEAT: add feature (wrong case)"
echo "  fix(Cart): resolve bug (scope should be lowercase)"
echo ""
echo "💡 Tips:"
echo "  - Use 'npm run commit' for interactive commit creation"
echo "  - Keep subject line under 72 characters"
echo "  - Use imperative mood (add, fix, update, not added, fixed, updated)"
echo "  - Reference issues: 'fix(auth): resolve login issue (#123)'"
