apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vendfinder

resources:
  - ../base
  - production-configs.yaml

labels:
- includeSelectors: true
  pairs:
    environment: production

images:
  - name: registry.digitalocean.com/vendfinder-registry/frontend
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/user-service
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/chat-service
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/product-service
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/order-service
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/websocket-service
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/support-bot
    newTag: latest
  - name: registry.digitalocean.com/vendfinder-registry/api-gateway
    newTag: latest