#!/bin/bash
# scripts/parity-analysis/lib/common.sh

set -euo pipefail

# Configuration loading
load_config() {
    local config_file="$1"
    if [[ ! -f "$config_file" ]]; then
        echo "ERROR: Config file not found: $config_file" >&2
        return 1
    fi
    echo "INFO: Loaded config from $config_file" >&2
}

# Logging functions
log_info() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] INFO: $*" >&2
}

log_warn() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARN: $*" >&2
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2
}

log_critical() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] CRITICAL: $*" >&2
}

# Report generation functions
init_report() {
    local report_file="$1"
    cat > "$report_file" << 'EOF'
# Production vs Staging Parity Analysis Report
Generated: $(date)

## Executive Summary
- **Environment:** Production vs Staging
- **Analysis Date:** $(date '+%Y-%m-%d %H:%M:%S')
- **Status:** In Progress

## Discrepancy Summary
EOF
}

add_discrepancy() {
    local report_file="$1"
    local priority="$2"
    local category="$3"
    local description="$4"
    local fix_command="${5:-N/A}"

    cat >> "$report_file" << EOF

### $priority: $category
**Issue:** $description
**Fix:** \`$fix_command\`
EOF
}

finalize_report() {
    local report_file="$1"
    local critical_count="$2"
    local high_count="$3"
    local medium_count="$4"
    local low_count="$5"

    cat >> "$report_file" << EOF

## Summary Counts
- **CRITICAL:** $critical_count (Must fix before production deployment)
- **HIGH:** $high_count (Fix within current sprint)
- **MEDIUM:** $medium_count (Address in next development cycle)
- **LOW:** $low_count (Backlog for future improvement)

## Next Steps
1. Address all CRITICAL discrepancies immediately
2. Plan HIGH priority fixes for current sprint
3. Schedule MEDIUM priority items for next cycle
4. Log LOW priority items in backlog

---
Report generated by VendFinder Parity Analysis System
EOF
}

# Validation functions
validate_tools() {
    local missing_tools=()

    command -v kubectl >/dev/null 2>&1 || missing_tools+=("kubectl")
    command -v jq >/dev/null 2>&1 || missing_tools+=("jq")
    command -v yq >/dev/null 2>&1 || missing_tools+=("yq")
    command -v curl >/dev/null 2>&1 || missing_tools+=("curl")
    command -v pg_dump >/dev/null 2>&1 || missing_tools+=("pg_dump")

    if [[ ${#missing_tools[@]} -gt 0 ]]; then
        log_error "Missing required tools: ${missing_tools[*]}"
        return 1
    fi

    log_info "All required tools available"
    return 0
}